### PR TITLE
fixed the bug issues

### PR DESCRIPTION
**Pull request by nfestasoftware**
The bug is fixed. 

please, could you review and provide your approvals for a merge!

Regards

peter
email: peter.jones@toyota@gmail.com

### CODE REVIEW

**Comment by nfestaclass02** [comment]
Approved.

**Comment by nfestasoftware** [comment]
review and confirmed merge

**Review by vessahboris — COMMENTED** [review]
great job!

**Comment by mukomleonele** [comment]
Amazing, approved!

**Pull request merged**
